listen: 7863

tls:
  cert: /app/hysteria/cert.pem
  key: /app/hysteria/key.pem

auth:
  type: password
  password: UUID

resolver:
  type: udp
  udp:
    addr: 8.8.8.8:53
    timeout: 4s

sniff:
  enable: true
  timeout: 2s
  tcpPorts: all
  udpPorts: all

acl:
  inline:
    - direct_local(domain:v.com)
    - direct(all)

outbounds:
  - name: direct
    type: direct
    direct:
      mode: 46
      fastOpen: false

  - name: direct_local
    type: direct
    direct:
      mode: 46
      bindIPv4: 127.0.0.1
      fastOpen: false